version: '3'

volumes:
  pg_data_production:
  static_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: hikari393/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - /var/www/kittygram/media/:/app/media/

  frontend:
    image: hikari393/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend


  gateway:
    image: hikari393/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend
    volumes:
      - static_volume:/staticfiles/
      - /var/www/kittygram/media/:/app/media/
    ports:
      - 9000:80